services:
 
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend_to_mongo

  app:
    build:
      context: backend
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/overcloud-db
    depends_on:
      - mongo
    restart: always


networks:
  default: